# Generated by Django 2.1 on 2018-12-31 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='response_id',
        ),
    ]
